{{ if .Values.schema.enabled }}
#{{ range .Values.schema.containers }}
{{ range $index, $container := .Values.schema.containers }}
---

apiVersion: batch/v1
kind: Job
metadata:
#  name: {{ $.Values.appName }}-{{ . }}-load
  name: {{ $.Values.appName }}-{{ $container }}-load
spec:
  template:
    spec:
      containers:
#      - name: {{ $.Values.appName }}-{{ . }}-load
      - name: {{ $.Values.appName }}-{{ $container }}-load
        image: 137068255381.dkr.ecr.us-east-1.amazonaws.com/roboshop-schema-load:latest
        imagePullPolicy: Always
        env:
          - name: SCHEMA_FILE
            value: db/{{ . }}.{{ $.Values.schema.dbExtention }}
        {{- range $k, $v := $.Values.schema.env }}
          - name: {{ $k }}
            value: {{ $v | quote }}
        {{- end }}
      restartPolicy: Never
  {{ if ne $index (sub (len .Values.schema.containers) 1) }}
  # This will add a `backoffLimit` to ensure the next job starts only when the previous one is successful.
  backoffLimit: 4
  {{ end }}
{{ end }}
{{ end }}
